spring:
  application:
    name: ws-rasmoo-plus
  datasource:
    url: jdbc:mysql://localhost:3306/RASPLUS
    username: rasmoo
    password: senha123
  flyway:
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: teste@gmail.com
    password: senha123
    properties:
      mail:
        smtp:
          auth: true
          start-tls:
            enable: true
  jpa:
    properties:
      hibernate:
        show_sql: true
  redis:
    host: localhost
    port: 6379

server:
  port: 8082
  servlet:
    context-path: /ws-rasplus

webservices:
  raspay:
    host: ${RASPAY_HOST:http://localhost:8081/ws-raspay}
    v1:
      customer: ${RASPAY_CUSTOMER:/v1/customer}
      order: ${RASPAY_ORDER:/v1/order}
      payment: ${RASPAY_PAYMENT:/v1/payment/credit-card/}
    credentials:
      user: rasmooplus
      password: r@sm00
    token:
      secret-key: 9399257a62c320e00e78945dff8a556cf5748ba4f136d61148271fcf1575243c
      expiration: 3600000

springdoc:
  swagger-ui:
    path: /rasmoo-documentation
    tryItOutEnabled: true
  api-docs:
    path: /rasmoo-api-docs
  packages-to-scan: com.client.ws.rasmooplus.controller
